StreamURL: "http://wtju.net:8000/wtjx-opus-256.ogg"
BaseSavePath: "."
Shows:
  Monday:
    - StartTime: "08:00"
      Duration: "2h"
    - StartTime: "06:00"
      Duration: "1hr"
  Saturday:
    - StartTime: "12:10"
      Duration: "1m"
