#StreamURL: "http://wtju.net:8000/wtjx-opus-256.ogg"
StreamURL: "http://wtju.net:8000/wtjx-128.mp3"
BaseSavePath: "."
Shows:
  Monday:
    - StartTime: "00:00"
      Duration: "2h"
    - StartTime: "08:00"
      Duration: "2h"
    - StartTime: "10:00"
      Duration: "2h"
    - StartTime: "12:00"
      Duration: "2h"
    - StartTime: "14:00"
      Duration: "2h"
    - StartTime: "16:00"
      Duration: "2h"
    - StartTime: "18:00"
      Duration: "2h"
    - StartTime: "20:00"
      Duration: "2h"
    - StartTime: "22:00"
      Duration: "2h"
  Tuesday:
    - StartTime: "00:00"
      Duration: "2h"
    - StartTime: "08:00"
      Duration: "2h"
    - StartTime: "10:00"
      Duration: "2h"
    - StartTime: "12:00"
      Duration: "2h"
    - StartTime: "14:00"
      Duration: "2h"
    - StartTime: "16:00"
      Duration: "2h"
    - StartTime: "18:00"
      Duration: "2h"
    - StartTime: "20:00"
      Duration: "2h"
    - StartTime: "22:00"
      Duration: "2h"
  Wednesday:
    - StartTime: "00:00"
      Duration: "2h"
    - StartTime: "08:00"
      Duration: "2h"
    - StartTime: "10:00"
      Duration: "2h"
    - StartTime: "12:00"
      Duration: "2h"
    - StartTime: "14:00"
      Duration: "2h"
    - StartTime: "16:00"
      Duration: "2h"
    - StartTime: "18:00"
      Duration: "2h"
    - StartTime: "20:00"
      Duration: "2h"
    - StartTime: "22:00"
      Duration: "2h"
  Thursday:
    - StartTime: "00:00"
      Duration: "2h"
    - StartTime: "08:00"
      Duration: "2h"
    - StartTime: "10:00"
      Duration: "2h"
    - StartTime: "12:00"
      Duration: "2h"
    - StartTime: "14:00"
      Duration: "2h"
    - StartTime: "16:00"
      Duration: "2h"
    - StartTime: "18:00"
      Duration: "2h"
    - StartTime: "20:00"
      Duration: "2h"
    - StartTime: "22:00"
      Duration: "2h"
  Friday:
    - StartTime: "00:00"
      Duration: "2h"
    - StartTime: "08:00"
      Duration: "2h"
    - StartTime: "10:00"
      Duration: "2h"
    - StartTime: "12:00"
      Duration: "2h"
    - StartTime: "14:00"
      Duration: "2h"
    - StartTime: "16:00"
      Duration: "2h"
    - StartTime: "18:00"
      Duration: "2h"
    - StartTime: "20:00"
      Duration: "2h"
    - StartTime: "22:00"
      Duration: "2h"
  Saturday:
    - StartTime: "00:00"
      Duration: "2h"
    - StartTime: "08:00"
      Duration: "2h"
    - StartTime: "10:00"
      Duration: "2h"
    - StartTime: "12:00"
      Duration: "2h"
    - StartTime: "14:00"
      Duration: "2h"
    - StartTime: "16:00"
      Duration: "2h"
    - StartTime: "18:00"
      Duration: "2h"
    - StartTime: "20:00"
      Duration: "2h"
    - StartTime: "22:00"
      Duration: "2h"
  Sunday:
    - StartTime: "00:00"
      Duration: "2h"
    - StartTime: "08:00"
      Duration: "2h"
    - StartTime: "10:00"
      Duration: "2h"
    - StartTime: "12:00"
      Duration: "2h"
    - StartTime: "14:00"
      Duration: "2h"
    - StartTime: "16:00"
      Duration: "2h"
    - StartTime: "18:00"
      Duration: "2h"
    - StartTime: "20:00"
      Duration: "2h"
    - StartTime: "22:00"
      Duration: "2h"
